name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set azure default
      run: az account set -s "ME-MngEnvMCAP548688-ramusti-1"
    - name: configure azure default
      run: az configure --defaults group=AMLLearning workspace=aml-rmusti-eastus
    - name: Trigger Azure Machine Learning job
      run: az ml job create --file src\job.yml


